export const scenarioFixtures = {
  healthy: {
    id: "healthy", label: "Healthy", overall: "TESTED CHECKS HEALTHY", tone: "pass",
    explanation: "The link is active, addressing is usable, and configured reachability checks completed. An LLDP advertisement supplied neighbor context.",
    next: ["Record the observed port and VLAN in the ticket.", "Continue with application-specific checks if the issue persists."],
    steps: [
      ["Ethernet Link", "PASS", "1 Gbps negotiated", "pass"],
      ["DHCP", "PASS", "10.20.120.51", "pass"],
      ["Gateway", "PASS", "10.20.120.1 · 4 ms", "pass"],
      ["DNS", "PASS", "10.10.10.20 · 9 ms", "pass"],
      ["Internet", "PASS", "TCP 1.1.1.1:443 · 18 ms", "pass"],
      ["LLDP/CDP", "OBSERVED", "LLDP advertisement", "observed"],
      ["Switch / Port", "OBSERVED", "swroc26d1a · ge-0/0/24", "observed"],
      ["Final health result", "PASS", "Bounded first-pass result", "pass"],
    ],
    details: [["Checks", "8 completed"], ["Duration", "1.8 sec"], ["IP", "10.20.120.51 / DHCP"], ["Gateway", "10.20.120.1"], ["DNS", "10.10.10.20"], ["VLAN", "120"], ["Switch", "swroc26d1a"], ["Port", "ge-0/0/24"], ["Protocol", "LLDP"]],
  },
  dhcp: { id: "dhcp", label: "DHCP Failure", overall: "ADDRESSING FAILED", tone: "fail", explanation: "The Ethernet link is active, but DHCP did not provide a usable address. Gateway, DNS, and Internet checks were not tested.", next: ["Check the access VLAN and DHCP scope.", "Compare with a known-good jack or static test only under your approved procedure."], steps: [["Ethernet Link","PASS","1 Gbps negotiated","pass"],["DHCP","FAIL","No lease obtained","fail"],["Gateway","NOT TESTED","Dependent check not run","unknown"],["DNS","NOT TESTED","Dependent check not run","unknown"],["Internet","NOT TESTED","Dependent check not run","unknown"],["LLDP/CDP","OBSERVED","LLDP advertisement","observed"],["Switch / Port","OBSERVED","swroc26d1a · ge-0/0/24","observed"],["Final health result","PARTIAL","Addressing requires review","partial"]], details:[["Link","1 Gbps negotiated"],["Address","Not assigned"],["Port","ge-0/0/24"],["VLAN","120"],["Neighbor","swroc26d1a"]]},
  dns: { id: "dns", label: "DNS Failure", overall: "NAME RESOLUTION FAILED", tone: "fail", explanation: "Link is active and DHCP succeeded, but DNS resolution failed. Internet reachability was not tested because the configured hostname could not be resolved.", next: ["Check the assigned DNS servers and resolver reachability.", "Compare resolution for an approved known-good name."], steps: [["Ethernet Link","PASS","1 Gbps negotiated","pass"],["DHCP","PASS","10.20.120.51","pass"],["Gateway","PASS","10.20.120.1 · 4 ms","pass"],["DNS","FAIL","10.10.10.20 · timeout","fail"],["Internet","NOT TESTED","Dependent check not run","unknown"],["LLDP/CDP","OBSERVED","LLDP advertisement","observed"],["Switch / Port","OBSERVED","swroc26d1a · ge-0/0/24","observed"],["Final health result","PARTIAL","Name resolution requires review","partial"]], details:[["IP","10.20.120.51 / DHCP"],["Gateway","10.20.120.1"],["DNS","10.10.10.20 · timeout"],["Port","ge-0/0/24"],["Neighbor","swroc26d1a"]]},
  gateway: { id: "gateway", label: "Gateway Unreachable", overall: "GATEWAY UNREACHABLE", tone: "fail", explanation: "The link and address are present, but the configured default gateway did not respond. DNS and Internet checks were not tested.", next: ["Check the local VLAN, gateway path, and access policy.", "Validate against another approved endpoint on the same segment."], steps: [["Ethernet Link","PASS","1 Gbps negotiated","pass"],["DHCP","PASS","10.20.120.51","pass"],["Gateway","FAIL","10.20.120.1 · timeout","fail"],["DNS","NOT TESTED","Dependent check not run","unknown"],["Internet","NOT TESTED","Dependent check not run","unknown"],["LLDP/CDP","OBSERVED","LLDP advertisement","observed"],["Switch / Port","OBSERVED","swroc26d1a · ge-0/0/24","observed"],["Final health result","PARTIAL","Default route requires review","partial"]], details:[["IP","10.20.120.51 / DHCP"],["Gateway","10.20.120.1 · timeout"],["DNS","Not tested"],["Port","ge-0/0/24"],["Neighbor","swroc26d1a"]]},
  neighbor: { id: "neighbor", label: "No LLDP/CDP", overall: "CONNECTIVITY HEALTHY", tone: "observed", explanation: "Basic connectivity checks passed. No LLDP/CDP advertisement was observed; that is a separate passive observation, not a connectivity failure.", next: ["Check whether the access environment advertises LLDP/CDP toward endpoints.", "Use the observed connectivity result without inferring a physical fault."], steps: [["Ethernet Link","PASS","1 Gbps negotiated","pass"],["DHCP","PASS","10.20.120.51","pass"],["Gateway","PASS","10.20.120.1 · 4 ms","pass"],["DNS","PASS","10.10.10.20 · 9 ms","pass"],["Internet","PASS","TCP 1.1.1.1:443 · 18 ms","pass"],["LLDP/CDP","NOT DETECTED","No advertisement observed","unknown"],["Switch / Port","NOT DETECTED","Not available from capture","unknown"],["Final health result","PASS","Connectivity passed; neighbor absent","pass"]], details:[["IP","10.20.120.51 / DHCP"],["Gateway","10.20.120.1"],["DNS","10.10.10.20"],["Neighbor","Not detected"],["Port","Not detected"]]},
  poe: { id: "poe", label: "PoE Issue", overall: "OUTSIDE CURRENT SCOPE", tone: "unknown", explanation: "LANVEXA can record the Ethernet/software observations shown here, but it does not perform PoE load testing or determine a PoE fault.", next: ["Use an approved physical-layer or PoE tester.", "Retain LANVEXA's connectivity observations as separate context."], steps: [["Ethernet Link","PASS","1 Gbps negotiated","pass"],["DHCP","PASS","10.20.120.51","pass"],["Gateway","PASS","10.20.120.1 · 4 ms","pass"],["DNS","PASS","10.10.10.20 · 9 ms","pass"],["Internet","PASS","TCP 1.1.1.1:443 · 18 ms","pass"],["LLDP/CDP","OBSERVED","LLDP advertisement","observed"],["Switch / Port","OBSERVED","swroc26d1a · ge-0/0/24","observed"],["Final health result","NOT TESTED","PoE is outside scope","unknown"]], details:[["Link","1 Gbps negotiated"],["IP","10.20.120.51 / DHCP"],["Port","ge-0/0/24"],["PoE","Not tested by LANVEXA"],["Boundary","Physical-layer tool required"]]},
};

